# Author: Livia Johan
# File: Makefile

# G++ is for the GCC compiler for C++
PP := g++

# CXXFLAGS are the compiler flages for when we compile C++ code in this course 
FLAGS := -O0 -g -Wall -Wextra -Wconversion -Wshadow -pedantic -Werror 
CXXFLAGS := -m64 -std=c++11 -Weffc++ $(FLAGS) 


INC := include
SRC := src
OBJ := obj
EXE := exe


# Command: make Fundamental
FundamentalObjs := $(OBJ)/Fundamental.o

Fundamental: $(FundamentalObjs)
	$(PP) $(CXXFLAGS) -o $(EXE)/Fundamental $(FundamentalObjs)
	$(EXE)/./Fundamental

$(OBJ)/Fundamental.o: $(SRC)/Fundamental.cpp
	$(PP) $(CXXFLAGS) -c $(SRC)/Fundamental.cpp -o $@


# Command: make PrintSorted
PrintSortedObjs := $(OBJ)/PrintSorted.o

PrintSorted: $(PrintSortedObjs)
	$(PP) $(CXXFLAGS) -o $(EXE)/PrintSorted $(PrintSortedObjs)
	$(EXE)/./PrintSorted

$(OBJ)/PrintSorted.o: $(SRC)/PrintSorted.cpp
	$(PP) $(CXXFLAGS) -c $(SRC)/PrintSorted.cpp -o $@


# make initialize
# W ill be called by grader to initialize your objects and executables folders

initialize: 
	mkdir $(OBJ) $(EXE)

#Make clean
clean :
	rm -rf *.o $(OBJ)/* $(EXE)/*
